export const MAKROSALINAN = [
    {   key : 't_2425_s_2',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_2425_s_1',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '1I7oy-1QML9JifmKIQr6aSFinHj41sMpNquhkigWyPEc',
        ss_nilai_2 : '1gS_unneUeDM6EhWbnLH_Jhb2rF_zGR-amwaQIj8z5-Y',
        ss_nilai_3 : '1ZBLhDtDNSD77lvS3inuRoH2ANmw8INdlnWNHDA97UR0',
        ss_nilai_4 : '13n_r-hzSSVMfl-sUqcYcTBENNSZYfLSwZUphqDvEJDw',
        ss_nilai_5 : '16JCg1cu8JuS6kqcYB02-1hOYPpeAEf8Z3N3x3a6U_No',
        ss_nilai_6 : '1ju-0JBxlVTr9SmzM-alckSiJefULj1tT5M9vEu6KJXg',
        //prefik
        tab_nilai_1 : 'nilai_raport_', // nilai_raport_<namaRombel>
        tab_nilai_2 : 'nilai_raport_', // nilai_raport_<namaRombel>
        tab_nilai_3 : 'nilai_raport_', // nilai_raport_<namaRombel>
        tab_nilai_4 : 'nilai_raport_', // nilai_raport_<namaRombel>
        tab_nilai_5 : 'nilai_raport_', // nilai_raport_<namaRombel>
        tab_nilai_6 : 'nilai_raport_', // nilai_raport_<namaRombel>
    },
    {   key : 't_2324_s_2',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '1WtavAL1wM-bAsZmcid3Wz4AJ71s_RAOF60MjQAJKgaw',
        ss_nilai_2 : '10rzdz-XRYR-bFk2rs9mIsveodkHLN9087mlHSschyMk',
        ss_nilai_3 : '1Utyb-feNGO-DdNvb_w_OUQQaTeZxKz6ua4zgMdE4yMw',
        ss_nilai_4 : '1C4-oT30yoSacDkEeDpXvCc2q85p5-Rhd27pCompkVMY',
        ss_nilai_5 : '1uF_nWXfpqOJEy23meO-UXWnFLRhI84jgqPMwf_kyxug',
        ss_nilai_6 : '1f8AbsyLwzdW3tPfdMjkKpnq4RY9uNDPxFSe-Khs7Row',
        //prefik
        tab_nilai_1 : 'nilai_raport_', // nilai_raport_<namaRombel>
        tab_nilai_2 : 'nilai_raport_', // nilai_raport_<namaRombel>
        tab_nilai_3 : 'nilai_raport_', // nilai_raport_<namaRombel>
        tab_nilai_4 : 'nilai_raport_', // nilai_raport_<namaRombel>
        tab_nilai_5 : 'nilai_raport_', // nilai_raport_<namaRombel>
        tab_nilai_6 : 'nilai_raport_', 
    },
    {   key : 't_2324_s_1',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '1yulRw8CLB-leNWtVQMcMQEg220ZZ8hbbUKRR0RtGbZw',
        ss_nilai_2 : '1fqJjdbL6hFrJsnOMTlDOtkbylgD7VGNNfw2IIkonn14',
        ss_nilai_3 : '1-PKYgOkjtgrwO3Qeblf1eoAvGLaM0TgNn7jBw9a5Ivo',
        ss_nilai_4 : '1k1ATRU4U4Ma1woeqV3ldtq6ySfIYsVQ-8PcraWaggdk',
        ss_nilai_5 : '153Bly4Hzna95roveDBl5Fwtbo1GUhI1yWYEuBrZGb50',
        ss_nilai_6 : '1yWpm9gWshW2VZZ_g-16QUYa1T2x_fVgI04nBkKqJZ3c',
        //prefik
        tab_nilai_1 : 'nilai_raport_',
        tab_nilai_2 : 'nilai_raport_',
        tab_nilai_3 : 'nilai_raport_',
        tab_nilai_4 : 'nilai_raport_',
        tab_nilai_5 : 'nilai_raport_',
        tab_nilai_6 : 'nilai_raport_',
    },
    {   key : 't_2223_s_2',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_2223_s_1',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_2122_s_2',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_2122_s_1',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_2021_s_2',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_2021_s_1',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_1920_s_2',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_1920_s_1',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_1819_s_2',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_1819_s_1',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_1718_s_2',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_1718_s_1',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_1617_s_2',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_1617_s_1',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_1516_s_2',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_1516_s_1',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_1415_s_2',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_1415_s_1',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_1314_s_2',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    {   key : 't_1314_s_1',
        //id spreadsheet salinan yang ada di folder DRIVE: BUKU INDUK
        ss_nilai_1 : '',
        ss_nilai_2 : '',
        ss_nilai_3 : '',
        ss_nilai_4 : '',
        ss_nilai_5 : '',
        ss_nilai_6 : '',
        //prefik
        tab_nilai_1 : '',
        tab_nilai_2 : '',
        tab_nilai_3 : '',
        tab_nilai_4 : '',
        tab_nilai_5 : '',
        tab_nilai_6 : '',
    },
    
];