export const MakroInduk = [
        {
            tapel   : 2526,
            idss    :'1uQISFu5BwgFWb08JYHeHnKiZd30YZcxMdp30_V1N4aY',
            kelas_1_kurikulum : 'kurmer',
            kelas_2_kurikulum : 'kurmer',
            kelas_3_kurikulum : 'kurmer',
            kelas_4_kurikulum : 'kurmer',
            kelas_5_kurikulum : 'kurmer',
            kelas_6_kurikulum : 'kurmer',
            kelas_1_mapel : ['PA','PKN','BINDO','MTK','RUPA','PJOK','BSUND'],
            kelas_2_mapel : ['PA','PKN','BINDO','MTK','RUPA','PJOK','BSUND'],
            kelas_3_mapel : ['PA','PKN','BINDO','MTK','IPAS','RUPA','PJOK','BSUND','BING'],
            kelas_4_mapel : ['PA','PKN','BINDO','MTK','IPAS','RUPA','PJOK','BSUND','BING'],
            kelas_5_mapel : ['PA','PKN','BINDO','MTK','IPAS','RUPA','PJOK','BSUND','BING'],
            kelas_6_mapel : ['PA','PKN','BINDO','MTK','IPAS','RUPA','PJOK','BSUND','BING'],
        },
        {
            tapel   : 2425,
            idss    :'1D9FXC4rr3Jmw9ifAd3U5NgmDNdB46j7NRys9PED69kg',
            kelas_1_kurikulum : 'kurmer',
            kelas_2_kurikulum : 'kurmer',
            kelas_3_kurikulum : 'kurmer',
            kelas_4_kurikulum : 'kurmer',
            kelas_5_kurikulum : 'kurmer',
            kelas_6_kurikulum : 'kurmer',
            kelas_1_mapel : ['PA','PKN','BINDO','MTK','RUPA','PJOK','BSUND',],
            kelas_2_mapel : ['PA','PKN','BINDO','MTK','RUPA','PJOK','BSUND',],
            kelas_3_mapel : ['PA','PKN','BINDO','MTK','IPAS','RUPA','PJOK','BSUND','BING'],
            kelas_4_mapel : ['PA','PKN','BINDO','MTK','IPAS','RUPA','PJOK','BSUND','BING'],
            kelas_5_mapel : ['PA','PKN','BINDO','MTK','IPAS','RUPA','PJOK','BSUND','BING'],
            kelas_6_mapel : ['PA','PKN','BINDO','MTK','IPAS','RUPA','PJOK','BSUND','BING'],
        },
        {
            tapel   : 2324,
            idss    :'1YSOCVKmFxUcMs9eSaV8uUMLyFPyzpv3INiozb8sWj78',
            kelas_1_kurikulum : 'kurmer',
            kelas_2_kurikulum : 'kurmer',
            kelas_3_kurikulum : 'kurtilas',
            kelas_4_kurikulum : 'kurmer',
            kelas_5_kurikulum : 'kurmer',
            kelas_6_kurikulum : 'kurtilas',
            
            kelas_1_mapel : ['PA','PKN','BINDO','MTK','RUPA','PJOK','BSUND',],
            kelas_2_mapel : ['PA','PKN','BINDO','MTK','RUPA','PJOK','BSUND',],
            kelas_3_mapel : ['PA','PKN','BINDO','MTK','SBDP','PJOK','BSUND'],
            kelas_4_mapel : ['PA','PKN','BINDO','MTK','IPAS','RUPA','PJOK','BSUND'],
            kelas_5_mapel : ['PA','PKN','BINDO','MTK','IPAS','RUPA','PJOK','BSUND'],
            kelas_6_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
        },
        {
            tapel   : 2223,
            idss    :'1GsvYdlBTwGX6_6vgSGUtfSg5iRlqsiTY8QnJzCqYbZE',
            kelas_1_kurikulum : 'kurmer',
            kelas_2_kurikulum : 'kurtilas',
            kelas_3_kurikulum : 'kurtilas',
            kelas_4_kurikulum : 'kurmer',
            kelas_5_kurikulum : 'kurtilas',
            kelas_6_kurikulum : 'kurtilas',
            kelas_1_mapel : ['PA','PKN','BINDO','MTK','RUPA','PJOK','BSUND',],
            kelas_2_mapel : ['PA','PKN','BINDO','MTK','SBDP','PJOK','BSUND'],
            kelas_3_mapel : ['PA','PKN','BINDO','MTK','SBDP','PJOK','BSUND'],
            kelas_4_mapel : ['PA','PKN','BINDO','MTK','IPAS','RUPA','PJOK','BSUND'],
            kelas_5_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_6_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
        },
        {
            tapel   : 2122,
            idss    :'1URPIM22N6oC_z4HH6df5zYulL3u_73iyh23MaR2N_po',
            kelas_1_kurikulum : 'kurtilas',
            kelas_2_kurikulum : 'kurtilas',
            kelas_3_kurikulum : 'kurtilas',
            kelas_4_kurikulum : 'kurtilas',
            kelas_5_kurikulum : 'kurtilas',
            kelas_6_kurikulum : 'kurtilas',
            kelas_1_mapel : ['PA','PKN','BINDO','MTK','SBDP','PJOK','BSUND'],
            kelas_2_mapel : ['PA','PKN','BINDO','MTK','SBDP','PJOK','BSUND'],
            kelas_3_mapel : ['PA','PKN','BINDO','MTK','SBDP','PJOK','BSUND'],
            kelas_4_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_5_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_6_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
        },
        {
            tapel   : 2021,
            idss    :'1H7BigaYVwE-3ldC_bgtzZC_L2mFA1gmn7NUwmmcr3gU',
            kelas_1_kurikulum : 'kurtilas',
            kelas_2_kurikulum : 'kurtilas',
            kelas_3_kurikulum : 'kurtilas',
            kelas_4_kurikulum : 'kurtilas',
            kelas_5_kurikulum : 'kurtilas',
            kelas_6_kurikulum : 'kurtilas',
            kelas_1_mapel : ['PA','PKN','BINDO','MTK','SBDP','PJOK','BSUND'],
            kelas_2_mapel : ['PA','PKN','BINDO','MTK','SBDP','PJOK','BSUND'],
            kelas_3_mapel : ['PA','PKN','BINDO','MTK','SBDP','PJOK','BSUND'],
            kelas_4_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_5_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_6_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
        },
        {
            tapel   : 1920,
            idss    :'1EBBkniX1o0O2R0Y_MtZdhZUo2vb1jAW3lgG_gL_4BX4',
            kelas_1_kurikulum : 'kurtilas',
            kelas_2_kurikulum : 'kurtilas',
            kelas_3_kurikulum : 'k2006',
            kelas_4_kurikulum : 'kurtilas',
            kelas_5_kurikulum : 'kurtilas',
            kelas_6_kurikulum : 'k2006',
            kelas_1_mapel : ['PA','PKN','BINDO','MTK','SBDP','PJOK','BSUND'],
            kelas_2_mapel : ['PA','PKN','BINDO','MTK','SBDP','PJOK','BSUND'],
            kelas_3_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_4_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_5_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_6_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
        },
        {
            tapel   : 1819,
            idss    :'1HHgQn-UdpzqdITQilTQpzKjLdVevkuN-7LitOvsVAD4',
            kelas_1_kurikulum : 'kurtilas',
            kelas_2_kurikulum : 'k2006',
            kelas_3_kurikulum : 'k2006',
            kelas_4_kurikulum : 'kurtilas',
            kelas_5_kurikulum : 'k2006',
            kelas_6_kurikulum : 'k2006',
            kelas_1_mapel : ['PA','PKN','BINDO','MTK','SBDP','PJOK','BSUND'],
            kelas_2_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_3_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_4_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_5_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_6_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
        },
        {
            tapel   : 1718,
            idss    :'1eVDJI8ard7WCUF4cMsnLS2znQOdDyN8kiQKEm-Z2MEg',
            kelas_1_kurikulum : 'k2006',
            kelas_2_kurikulum : 'k2006',
            kelas_3_kurikulum : 'k2006',
            kelas_4_kurikulum : 'k2006',
            kelas_5_kurikulum : 'k2006',
            kelas_6_kurikulum : 'k2006',
            kelas_1_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_2_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_3_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_4_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_5_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_6_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
        },
        {
            tapel   : 1617,
            idss    :'1Pvc5G3Ui9KWCrS2SP1y_wLrObZp-m-YnUltoCVGsuoU',
            kelas_1_kurikulum : 'k2006',
            kelas_2_kurikulum : 'k2006',
            kelas_3_kurikulum : 'k2006',
            kelas_4_kurikulum : 'k2006',
            kelas_5_kurikulum : 'k2006',
            kelas_6_kurikulum : 'k2006',
            kelas_1_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_2_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_3_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_4_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_5_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_6_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
        },
        {
            tapel   : 1516,
            idss    :'1NsGMNfDGvcP4E6_c9wa5UEHCt8YLoFLYEcb7-Dnghws',
            kelas_1_kurikulum : 'k2006',
            kelas_2_kurikulum : 'k2006',
            kelas_3_kurikulum : 'k2006',
            kelas_4_kurikulum : 'k2006',
            kelas_5_kurikulum : 'k2006',
            kelas_6_kurikulum : 'k2006',
            kelas_1_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_2_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_3_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_4_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_5_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_6_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
        },
        {
            tapel   : 1415,
            idss    :'1wNIeJT3KNwwtzlMCXzIPN9abUK1YMIpsltXB0sUrvK8',
            kelas_1_kurikulum : 'k2006',
            kelas_2_kurikulum : 'k2006',
            kelas_3_kurikulum : 'k2006',
            kelas_4_kurikulum : 'k2006',
            kelas_5_kurikulum : 'k2006',
            kelas_6_kurikulum : 'k2006',
            kelas_1_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_2_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_3_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_4_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_5_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_6_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
        },
        {
            tapel   : 1314,
            idss    :'15tDxLwYWHVJaWFKJ7RZsMoYmSDouDBz8ckqVwRmxyYQ',
            kelas_1_kurikulum : 'k2006',
            kelas_2_kurikulum : 'k2006',
            kelas_3_kurikulum : 'k2006',
            kelas_4_kurikulum : 'k2006',
            kelas_5_kurikulum : 'k2006',
            kelas_6_kurikulum : 'k2006',
            kelas_1_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_2_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_3_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_4_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_5_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
            kelas_6_mapel : ['PA','PKN','BINDO','MTK','IPA','IPS','SBDP','PJOK','BSUND'],
        },
    ];



